name: Build Kernel - Tab A7 (SM-T500)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by Joao
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        path: kernel_source
        fetch-depth: 1

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev ccache libelf-dev clang lld python3
        
    - name: Download Proton Clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang

    - name: A Grande Limpeza (Hack dos Submodulos)
      working-directory: kernel_source
      run: |
        # 1. Explodimos o arquivo de submodulos para o Git parar de dar erro 128
        rm -f .gitmodules
        
        # 2. Baixamos o ReSukiSU (KernelSU modificado do DevCat3) na mão!
        rm -rf KernelSU
        git clone https://github.com/ReSukiSU/ReSukiSU KernelSU
        
        # 3. Enganamos o compilador criando arquivos vazios para os mods fantasmas
        mkdir -p security/baseband-guard
        touch security/baseband-guard/Kconfig
        touch security/baseband-guard/Makefile
        
        mkdir -p nomount
        touch nomount/Kconfig
        touch nomount/Makefile
        
        mkdir -p Baseband-guard
        touch Baseband-guard/Kconfig
        touch Baseband-guard/Makefile

    - name: Build the Kernel
      working-directory: kernel_source
      run: |
        export PATH="$GITHUB_WORKSPACE/clang/bin:$PATH"
        export ARCH=arm64
        export SUBARCH=arm64
        
        # Trava de segurança para o KernelSU
        if [ ! -f "drivers/kernelsu/Kconfig" ]; then
            echo "Corrigindo o caminho do KernelSU..."
            ln -sf ../KernelSU drivers/kernelsu
        fi
        
        # Gerando o .config
        make O=out ARCH=arm64 gta4l_eur_open_defconfig
        
        # A Compilação pesada (A Forja)
        make -j$(nproc) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1
        
    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb
        path: kernel_source/out/arch/arm64/boot/Image.gz-dtb
