name: Build Kernel - Tab A7 (SM-T500)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by Joao
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        path: kernel_source
        fetch-depth: 1

    - name: O Exorcismo do Baseband-guard (Fix Submodules)
      working-directory: kernel_source
      run: |
        # Remove a referência do submódulo quebrado para não travar o git
        git config --file .gitmodules --remove-section submodule.Baseband-guard || true
        git rm --cached Baseband-guard || true
        rm -rf Baseband-guard || true
        
        # Agora sim, atualiza apenas os submódulos saudáveis (como o KernelSU)
        git submodule update --init --recursive

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev ccache libelf-dev clang lld python3
        
    - name: Download Proton Clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang
        
    - name: Build the Kernel
      working-directory: kernel_source
      run: |
        export PATH="$GITHUB_WORKSPACE/clang/bin:$PATH"
        export ARCH=arm64
        export SUBARCH=arm64
        
        # Trava de segurança para o KernelSU (Caso o DevCat3 tenha colocado na raiz)
        if [ ! -f "drivers/kernelsu/Kconfig" ] && [ -d "KernelSU" ]; then
            echo "Corrigindo o caminho do KernelSU..."
            ln -sf ../KernelSU drivers/kernelsu
        fi
        
        # Gerando o .config
        make O=out ARCH=arm64 gta4l_eur_open_defconfig
        
        # A Compilação pesada
        make -j$(nproc) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1
        
    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb
        path: kernel_source/out/arch/arm64/boot/Image.gz-dtb
